name: Win-2019 RDP

on: 
  workflow_dispatch:
    inputs:
      unk:
        description: 'stub input'
        required: false
        default: false


jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Test foreground
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: ${{ secrets.USER_PASS }}
    # ngrok should exit now
    - name: Test background
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: ${{ secrets.USER_PASS }}
        foreground: false
    # ngrok should be still running, so this should not create new ngrok, but should detects ngrok exit correctly
    - name: Test foreground
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: ${{ secrets.USER_PASS }}
    # post check should be working
    - name: Test background
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: ${{ secrets.USER_PASS }}
        foreground: false
